name: Juprec Docker Deployment

# Trigger only on push to the main branch
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install jq for JSON Parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create Folder
        run: mkdir -p juprec_docker/resources

      - name: Get Juprec Docker Resources
        run: |
          GITHUB_BASE_URL="https://raw.githubusercontent.com/ellavondegurechaff/juprecresources/main/docker"
          
          # ContainerFile
          curl -L "$GITHUB_BASE_URL/Containerfile" -o juprec_docker/Containerfile

          # NGINX Files
          curl -L "$GITHUB_BASE_URL/nginx/nginx-entrypoint.sh" -o juprec_docker/resources/nginx-entrypoint.sh
          curl -L "$GITHUB_BASE_URL/nginx/nginx-template.conf" -o juprec_docker/resources/nginx-template.conf

          # PWD File
          curl -L "$GITHUB_BASE_URL/pwd/pwd.yml" -o juprec_docker/pwd-dev.yml

          # Apps JSON File
          curl -L "$GITHUB_BASE_URL/apps/apps.json" -o juprec_docker/apps-dev.json

      - name: Encode apps.json To Base64
        run: |
          export APPS_JSON_BASE64=$(base64 -w 0 juprec_docker/apps-dev.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          APPS_JSON_BASE64: ${{ env.APPS_JSON_BASE64 }}
        run: |
          docker build \
            --build-arg FRAPPE_PATH=https://github.com/frappe/frappe \
            --build-arg FRAPPE_BRANCH=version-15 \
            --build-arg PYTHON_VERSION=3.10.12 \
            --build-arg NODE_VERSION=18 \
            --build-arg APPS_JSON_BASE64=$APPS_JSON_BASE64 \
            --tag=juprec-dev:latest \
            --file=juprec_docker/Containerfile .

      - name: Start Services
        run: sudo docker compose -p juprec-dev -f juprec_docker/pwd-dev.yml up -d

      - name: Check Site Logs
        run: sudo docker logs juprec-dev-create-site-1 -f

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no juprec_docker/pwd-dev.yml $VPS_USER@$VPS_HOST:/tmp/
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
            sudo docker compose -p juprec-dev -f /tmp/pwd-dev.yml up -d
          EOF
