name: Juprec Docker Deployment

# Trigger only on push to the main branchs
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install jq for JSON Parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create Folder
        run: mkdir -p juprec_docker/resources

      - name: Get Juprec Docker Resources
        run: |
          GITHUB_BASE_URL="https://raw.githubusercontent.com/ellavondegurechaff/juprecresources/main"

          # Download Containerfile to the root of the context directory
          curl -f -L "$GITHUB_BASE_URL/Containerfile" -o juprec_docker/Containerfile || { echo "Failed to download Containerfile"; exit 1; }

          # Download NGINX Files
          curl -f -L "$GITHUB_BASE_URL/nginx/nginx-entrypoint.sh" -o juprec_docker/resources/nginx-entrypoint.sh || { echo "Failed to download nginx-entrypoint.sh"; exit 1; }
          curl -f -L "$GITHUB_BASE_URL/nginx/nginx-template.conf" -o juprec_docker/resources/nginx-template.conf || { echo "Failed to download nginx-template.conf"; exit 1; }

          # Download PWD File
          curl -f -L "$GITHUB_BASE_URL/pwd/pwd.yml" -o juprec_docker/pwd.yml || { echo "Failed to download pwd.yml"; exit 1; }

          # Download Apps JSON File
          curl -f -L "$GITHUB_BASE_URL/apps/apps.json" -o juprec_docker/apps.json || { echo "Failed to download apps.json"; exit 1; }

      - name: List Downloaded Files
        run: ls -R juprec_docker

      - name: Print PWD File Content
        run: cat juprec_docker/pwd.yml

      - name: Encode apps.json To Base64
        run: |
          export APPS_JSON_BASE64=$(base64 -w 0 juprec_docker/apps.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - name: Build Docker Image
        env:
          APPS_JSON_BASE64: ${{ env.APPS_JSON_BASE64 }}
        run: |
          docker build \
            --build-arg FRAPPE_PATH=https://github.com/frappe/frappe \
            --build-arg FRAPPE_BRANCH=version-15 \
            --build-arg NODE_VERSION=18.18.2 \
            --build-arg PYTHON_VERSION=3.11.6 \
            --build-arg APPS_JSON_BASE64=$APPS_JSON_BASE64 \
            --tag=juprec-dev:latest \
            --file=juprec_docker/Containerfile juprec_docker

      - name: Start Services
        run: sudo docker compose -p juprec-dev -f juprec_docker/pwd.yml up -d

      - name: Check Site Logs
        run: sudo docker logs juprec-dev-create-site-1 -f
